language: node_js
node_js: node
os:
- linux
- osx
dist: trusty
sudo: true
git:
  depth: 3

install:
  - bash ./.travis/install.sh
  - bash ./.travis/run.sh
  - npm install
  
test_script:
  - npm --version

notifications:
  email:
    on_success: never
